### ISSUE TITLE
Usage Request - Binding-ToVisibility

### ISSUE THREAD

**Issue by ceeSharpFan** [ABTSoftware/SciChart.Wpf.UI#1]
I have a bool in my viewModel:
IsDestinationSet

I would like to bind the visibility to it:
  tz:Transitionz.Opacity="{tz:OpacityParams Duration=2000, From=0, To=1, TransitionOn=Visibility}"
  tz:Transitionz.Blur="{tz:BlurParams Duration=2000, From=20, To=0,TransitionOn=Visibility}"
 tz:Transitionz.Translate="{tz:TranslateParams From='10,0', To='0,0', Duration=200, TransitionOn=Visibility}"
 tz:Transitionz.Visibility="{Binding Path=IsDestinationSet, Converter={StaticResource b2destination}}"

I cant seem to get the event to ever fire, the markup is for a stackpanel.

Could you please provide an example of changing the visibility from a view model property(collapsed/Visible)

**Comment by andyb1979** [comment]
Can you share the code for b2destination converter please?

Also check for binding errors in the output window. It is possible that your binding is failing.

**Comment by ceeSharpFan** [comment]
Andy,
Thanks for the quick reply and thank you for building the library, i searched for hours on applying simple animations as i would in HTML using jquery. This is exactly what im looking for and unfortunately i just cant seem to get it working right....

I have two stack panels, one collapsed, one showing, when the destination is set in the view model, i effectively want to hide the "spChooseLocation" stack panel and show the "spChooseDestination", i also need to be able to "toggle" one showing, the other hidden. Please bare with me as im trying to leearn WPF, and PRISM as i build.

**Comment by ceeSharpFan** [comment]
I initally tried:

 `  tz:Transitionz.Visibility="{Binding IsDestinationSet}"

//View Model
  public bool IsDestinationSet
        {
            get
            {
                return !string.IsNullOrWhiteSpace(Destination);
            }
        }
`

**Comment by andyb1979** [comment]
I modified the test app in this commit to demonstrate Transitionz.Opacity, Translate triggered on Visibility via a view model boolean property. Please see commit https://github.com/ABTSoftware/SciChart.Wpf.UI/commit/0ebcd888ad116a400fce85b3da401cae5d311043#diff-ff0575ac3df3bf5fe77751fe9160f290

Transitionz.Blur it appears does not support Visibility, only being activated once. You can however bind Transition.Blur straight to a BlurParams object in your view model if you want to trigger blur changes. To see an example, please see the Wiki for Transitionz. https://github.com/ABTSoftware/SciChart.Wpf.UI/wiki/Transitionz-Library

**Comment by ceeSharpFan** [comment]
Thank You, giving it a go now!

**Comment by ceeSharpFan** [comment]
Works like a charm, thanks for your work.

**Comment by andyb1979** [comment]
You're very welcome! 👍
