### ISSUE TITLE
ScaleParamsExtencion is not a valid value for LayoutScale.

### ISSUE THREAD

**Issue by Jerajo** [ABTSoftware/SciChart.Wpf.UI#4]
I am getting a error with this transition.

```XAML
<Image Source="/POAR Estudios;component/Images/Logo.png" 
Width="250" tz:Transitionz.LayoutScale="{tz:ScaleParams AutoReverse=True, Duration=2000, 
From='10,0', To='0,0', TransitionOn=Loaded}"/>`

**ERROR**
`ScaleParamsExtencion is not a valid value for LayoutScale.`

I don't know what I'm doing bad.

**Comment by andyb1979** [comment]
It should be ... tz:Transitionz.Scale = {tz:ScaleParams}

can you try that?

**Comment by Jerajo** [comment]
It said Scale is not reconice or is not accessible.

**Comment by Symbai** [comment]
Same here, using latest nuget

**Comment by andyb1979** [comment]
We'll take a look

**Comment by andyb1979** [comment]
Hi guys, try commit 4cdddec714fb162cb0f2b1a6b154872acdd7988a, this should fix the above. 

Also we're doing some testing on number of small issues related to TransitionOn.Loaded so if you give us your feedback soon we can include these and your fix in a NuGet package update. 

Best regards, 
Andrew

**Comment by andyb1979** [comment]
Try package [2.1.41](https://www.nuget.org/packages/SciChart.Wpf.UI.Transitionz/2.1.41) which is now on NuGet

**Comment by Jerajo** [comment]
Thanks @andyb1979
