### ISSUE TITLE
Transition between two labels not working as expected

### ISSUE THREAD

**Issue by btastic** [ABTSoftware/SciChart.Wpf.UI#5]
First off, thank you for this library, it is really looking promising.

However, here is something I don't quite understand how to work around or set up.

The full code for a repro is here: https://github.com/btastic/transitionzrepro

The problem is that when I want to transition between two labels, after the first transition and then back, the first label is a bit off where it was before. I can't describe it good enough I think, so here is a gif that shows what I mean:

![gif](https://github.com/btastic/transitionzrepro/blob/master/repro.gif?raw=true)

I think maybe it has to do something with the reverse stuff in the transition? But I am not sure.

The xaml:
```xaml
<Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="50" />
            <RowDefinition Height="*" />
        </Grid.RowDefinitions>
        <CheckBox
            Grid.Row="0"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            Content="YAY"
            IsChecked="{Binding IsDoingStuff}" />
        <Label
            Grid.Row="1"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            tz:Transitionz.Opacity="{tz:OpacityParams From=0,
                                                      To=1,
                                                      Duration=500,
                                                      TransitionOn=Visibility}"
            tz:Transitionz.Translate="{tz:TranslateParams From='0,0',
                                                          To='10,0',
                                                          AutoReverse=False,
                                                          Duration=500,
                                                          TransitionOn=Visibility}"
            tz:Transitionz.Visibility="{Binding IsDoingStuff, Converter={StaticResource ResourceKey=InvBoolToVisibilityConverter}}"
            Content="NOT YAY"
            Visibility="{Binding IsDoingStuff, Converter={StaticResource ResourceKey=InvBoolToVisibilityConverter}}" />

        <Label
            Grid.Row="1"
            HorizontalAlignment="Center"
            VerticalAlignment="Center"
            tz:Transitionz.Opacity="{tz:OpacityParams From=0,
                                                      To=1,
                                                      Duration=500,
                                                      TransitionOn=Visibility}"
            tz:Transitionz.Translate="{tz:TranslateParams From='10,0',
                                                          To='0,0',
                                                          AutoReverse=False,
                                                          Duration=500,
                                                          TransitionOn=Visibility}"
            tz:Transitionz.Visibility="{Binding IsDoingStuff, Converter={StaticResource ResourceKey=BoolToVisibilityConverter}}"
            Content="YAY"
            Visibility="{Binding IsDoingStuff, Converter={StaticResource ResourceKey=BoolToVisibilityConverter}}" />
    </Grid>
```

I really would appreciate your help!

Thank you

**Comment by btastic** [comment]
After pulling master it worked. Seemed to be this bug? https://github.com/ABTSoftware/SciChart.Wpf.UI/commit/9076ae6d2abf81d7214e29491cf283ace6c648bb

When do you release a new nuget package?

**Comment by andyb1979** [comment]
Hi Ben

Sounds about right. I’m doing a bit of work on the bootstrap and reactive packages and publishing to a private nugget feed here:  https://www.myget.org/gallery/abtsoftware-bleeding-edge

I havent promoted them to nuget.org yet as a.) they have breaking changes and b.) I’m constabtly updating these packages which I’m using in a few WPF apps

If you’re just using Transitionz the breaking changes shouldn’t bother you too much. I could potentially push just this package to nuget as it has less development than the others

**Comment by btastic** [comment]
Hey Andy,

thank you so much for the quick response. I will stick with a submodule for now until a new nuget version has been pushed. Is it possible to give me a quick heads up once you pushed a new nuget package to the public feed?

Thank you!

**Comment by andyb1979** [comment]
Transitionz 2.0.38 is published to NuGet now. I'm trying to push the others (UI.Reactive and UI.Bootstrap) but having issues. 

Would be good for me to get a demo of these packages as well -- I'm using them in a few WPF apps to integrate Rx (Reactive extensions) with INotifyPropertyChanged and MVVM ... 

Have a good day! 
![smooth-ui](https://user-images.githubusercontent.com/14041557/45597290-cb927580-b9c1-11e8-9ac8-c834ca851016.gif)

**Comment by btastic** [comment]
It worked. Thank you very much!
